development:
  adapter: postgresql
  database: mimo_spree_example_development
  username: root
  encoding: utf8
  host: 127.0.0.1

test:
  adapter: postgresql
  database: mimo_spree_example_test
  username: root
  encoding: utf8
  host: 127.0.0.1
